api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "3a73b661189bcf7012edefb8e16922a991801833b8b3af25f7bea526a5dc8843"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.228.tar.gz"
    source_sha256 = "8e83ee18db5b4591155c00d38f3069bf0dbd865f88cfe5a85b45793e39edf0c6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.228/node-engine-0.0.228.tgz"
    version = "0.0.228"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "af1cb4e56f540173e3105705236874278089b36df16addc5ed34b197714e6cfd"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.54.tar.gz"
    source_sha256 = "d92e61fd46349322d16bed2c6184e833770520226614feb42f774b5f2335a77b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.54/npm-0.1.54.tgz"
    version = "0.1.54"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "43c72d800f8ccbba3fd4e3850ab07191d8c765a76aa87f647bba043c58f7dce4"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.62.tar.gz"
    source_sha256 = "50ee89ccaf601066907dc84b749129b605bf7b3b4505627d4fbae12be155f82e"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.62/yarn-install-0.1.62.tgz"
    version = "0.1.62"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.228"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.62"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.228"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.54"
