api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "6c5d1bdc021101493a3a082cc713583f0e7ff9aeef73e825c1ed05fd6ca92d48"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.216.tar.gz"
    source_sha256 = "63fd1ad0490cfdcf7581077dc33e779b21d6eeaae42a6de064bb8823d930484c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.216/node-engine-0.0.216.tgz"
    version = "0.0.216"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "1eb059f5a465ef76e2ed65a8b0464d16b893462caf81b0bacc02237a0af9d749"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.43.tar.gz"
    source_sha256 = "eb33fb109820c242fbfe76aa9ed4b0c1f8d459834b9e57b3903799d48b355de7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.43/npm-0.1.43.tgz"
    version = "0.1.43"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "4eb209aad14ce14a4216f536d97689ccc1c2af9551979a3d24c88a6e8bd51cfb"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.53.tar.gz"
    source_sha256 = "ffa115ec1a8068237497158495d50739171ea9d11dc3de10905ebeaa85ed49bf"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.53/yarn-install-0.1.53.tgz"
    version = "0.1.53"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.216"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.53"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.216"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.43"
