api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "ab1c7e3be23245f3550d5b9c376407dc0f53f43b846ebcb438547dd794bb48f7"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.210.tar.gz"
    source_sha256 = "8e0528307e60f36808219eba367afb235406fcb6be07c57b85dc8d94673e0d53"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.210/node-engine-0.0.210.tgz"
    version = "0.0.210"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "5118b04d8cd5400dde51e2377cccc52731c5e2cf8dcb63ce3446b1de5108eb61"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.34.tar.gz"
    source_sha256 = "8ee74feabf80c5653def8971c0349a1335c2ff26fccb2bc65e9ef8db54b992ec"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.34/npm-0.1.34.tgz"
    version = "0.1.34"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "1a3244360a2b991d07906fd22e04c04a94b76ac88a8ff240c0a153a2cbc99d30"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.44.tar.gz"
    source_sha256 = "3bd0e3bdfbef80e8a8671cb023cce3a66e0e370032d0f2bf60eb3c70460df37d"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.44/yarn-install-0.1.44.tgz"
    version = "0.1.44"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.210"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.44"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.210"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.34"
