api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "808acf5931971633e017528d42f78f3f07942cbc22a2cd9d2e2f517f088b125e"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.232.tar.gz"
    source_sha256 = "c9947ad3198242734f2dc3e77c47c118ccf81a0c2f4b975766a7505b3cd8e4f2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.232/node-engine-0.0.232.tgz"
    version = "0.0.232"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "4c3a2ec43f6ba351222627a5d503c524fb032126db9dae6140b1228c66bd5346"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.58.tar.gz"
    source_sha256 = "6d1b0433be9a78339b013e06c7ea575758a7be5d25bcb531c5b3ffae84e1ba3a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.58/npm-0.1.58.tgz"
    version = "0.1.58"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "84a513a894051287d2ce04bececd27da7b193023c12e3e5e04586afcc1237c50"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.65.tar.gz"
    source_sha256 = "cec521b48df9409c1d119fc146abcbc6e5fdb3fa0f208cb76aaf0ec14aeb9179"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.65/yarn-install-0.1.65.tgz"
    version = "0.1.65"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.232"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.65"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.232"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.58"
